var x = new SampleApplication_ClientSide_Tests.GeneratedClassesTests.ViewModel.JsonDeserializationTests();
x.runTests();
x = new SampleApplication_ClientSide_Tests.BaseClassesTests.View.ViewTests();
x.runTests();
x = new SampleApplication_ClientSide_Tests.BaseClassesTests.View.ViewModelTests();
x.runTests();
x = new SampleApplication_ClientSide_Tests.BaseClassesTests.View.ViewModelCollectionTests();
x.runTests();
x = new SampleApplication_ClientSide_Tests.BaseClassesTests.View.RouterTests();
x.runTests();
